- name: Déploiement de l'agent FusionInventory
  hosts: all
  become: true
  tags: fusioninventory
  tasks:
    - name: Mise à joure du système via apt update avec --allow-releaseinfo-change
      command: apt update --allow-releaseinfo-change

    - name: Installation du paquet FusionInventory-Agent
      package:
        name: fusioninventory-agent
        state: present

    - name: Configuration de l'agent FusionInventory
      lineinfile:
        path: /etc/fusioninventory/agent.cfg
        regex: '^server'
        line: 'server = http://192.168.57.98/glpi/plugins/fusioninventory/'
      
    - name: Redémarrage de l'agent FusionInventory 
      command: fusioninventory-agent

- name: Déploiement de Nagios
  hosts: localhost
  become: true
  tags: nagios
  tasks:
    - name: Configuration de Nagios
      command: /home/tprli/config-nagios.sh
      
    - name: Redémarrage de Nagios
      command: systemctl restart nagios4